### ISSUE TITLE
Splash screen, App Icon and App name

### ISSUE THREAD

**Issue by agent515** [agent515/doc_scanner#2]
**Tasks:**
- [ ] Suggest a suitable and catchy App-name
- [ ] Find or create an App-Icon
- [ ] Design and build a Splash screen
